name:                gearhash
version:             1.0.0
github:              "gkleen/fastcdc/gearhash"
license:             BSD3
license-file:        LICENSE
author:              "Gregor Kleen"
maintainer:          "aethoago@141.li"
copyright:           "2022 Gregor Kleen"
synopsis:            "An implementation of Gear hash, a fast rolling hash algorithm"

dependencies:
  - base >= 4.7 && < 5
  - array >= 0.5.4 && < 0.6
  - template-haskell >= 2.16 && < 2.17
  - bytestring >= 0.10 && < 0.12
  - th-lift-instances >= 0.1.16 && < 0.2
  - cryptonite >= 0.24 && < 0.30
  - conduit >= 1.3 && < 1.4
  - mtl >= 2.2 && < 3
  - bv-little >= 1.1 && < 2

default-extensions:
  - NoImplicitPrelude

other-extensions:
  - DeriveGeneric
  - DeriveDataTypeable
  - RecordWildCards
  - TemplateHaskell
  - TupleSections
  - ExplicitForAll
  - TypeFamilies
  - BangPatterns

when:
  - condition: flag(pedantic)
    ghc-options:
      - -Werror

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Data.Digest.GearHash
    - Data.Digest.GearHash.Conduit

executables:
  gearhash:
    source-dirs: gearhash
    main: Direct.hs
    other-modules: []
    dependencies:
      - gearhash
  gearhash-conduit:
    source-dirs: gearhash
    main: Conduit.hs
    other-modules: []
    dependencies:
      - gearhash
  count:
    source-dirs: gearhash
    main: Count.hs
    other-modules: []

flags:
  pedantic:
    manual: true
    default: false
