name:                fastcdc
version:             0.0.0
github:              "gkleen/fastcdc/fastcdc"
license:             BSD3
license-file:        LICENSE
author:              "Gregor Kleen"
maintainer:          "aethoago@141.li"
copyright:           "2022 Gregor Kleen"
synopsis:            "An implementation of FastCDC, a content-defined chunking algorithm based on the Gear hash rolling hash algorithm"

dependencies:
  - base >= 4.7 && < 5
  - gearhash >= 0.0 && < 2
  - conduit >= 1.3 && < 1.4
  - bytestring >= 0.10 && < 0.11
  - bv-little >= 1.1 && < 2

default-extensions:
  - NoImplicitPrelude

other-extensions:
  - BangPatterns
  - PatternGuards
  - RecordWildCards
  - ScopedTypeVariables
  - DeriveGeneric
  - DeriveDataTypeable

when:
  - condition: flag(pedantic)
    ghc-options:
      - -Werror

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Data.Conduit.Algorithms.FastCDC

executables:
  fastcdc:
    source-dirs: fastcdc
    main: Main.hs
    other-modules: []
    dependencies:
      - fastcdc

flags:
  pedantic:
    manual: true
    default: false
